#!/usr/bin/env bash
# Configuring 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\ntrewrite ^\/redirect_me https:\/\/github.com\/amarquaye permanent;"

sudo sed -i "string_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 page
echo "Ceci n'est pas une page" | sudo te /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/ 404.html;\n\tlocation = \/ 404.html {\n\t\troot \/var/\ww\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listern 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default 

sudo service restart


